GET http://localhost:3000/api/posts 
###
GET http://localhost:3000/api/posts/3
###
POST http://localhost:3000/api/posts
Content-Type: application/json

{
  "title": "Node js",
  "body": "Node is using express"
} 
### req.body 